[[constraint]]
  name = "github.com/spotahome/kooper"
  version = "v0.1.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.1"

[[override]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.7"
