{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - extensions
    resources:
      - pods
    verbs:
      - delete
      - deletecollection
{{- end }}
