apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: operator
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "operator.fullname" . }}
spec:
  template:
    metadata:
    {{- if .Values.operator.podAnnotations }}
      annotations:
{{ toYaml .Values.operator.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "name" . }}
        component: operator
        release: {{ .Release.Name }}
      {{- if .Values.operator.podLabels }}
{{ toYaml .Values.operator.podLabels | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ template "name" . }}-operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: "{{ .Values.operator.image.pullPolicy }}"
          args:
            - -config {{ .Values.operator.configPath }}
            - -listenaddr {{ .Values.operator.port }}
            - -loglevel {{ .Values.operator.logLevel }}
          {{- range .Values.operator.plugins }}
            - -plugin {{ . }}
          {{- end }}
          env:
            - name: AWS_REGION
              value: "{{ .Values.awsRegion }}"
          {{- range $key, $value := .Values.operator.extraEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - containerPort: {{ .Values.operator.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.operator.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: {{ .Values.operator.readinessProbeInterval }}
        {{- if .Values.operator.resources }}
          resources:
{{ toYaml .Values.operator.resources | indent 12 }}
        {{- end }}
        {{- if .Values.sidecarContainers }}
{{ toYaml .Values.sidecarContainers | indent 8}}
        {{- end }}
    {{- if .Values.operator.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.operator.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.operator.tolerations }}
      tolerations:
{{ toYaml .Values.operator.tolerations | indent 8 }}
    {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      terminationGracePeriodSeconds: 60
