# Quay.io doesn't allow container image & application repositories in the same organization
# to share a name. In this case, the image is quay.io/coreos/alb-ingress-controller,
# and the Helm chart is quay.io/coreos/alb-ingress-controller-helm. This variable
# overrides the chart name.
nameOverride: alb-ingress-controller

## AWS region in which this ingress controller will operate
## REQUIRED
#
awsRegion: us-west-1

## Resources created by the ALB Ingress controller will be prefixed with this string
## REQUIRED
#
clusterName: k8s

operator:
  image:
    repository: quay.io/coreos/alb-ingress-controller
    tag: "0.8"
    pullPolicy: IfNotPresent

  extraEnv: {}
    # AWS_ACCESS_KEY_ID: ""
    # AWS_SECRET_ACCESS_KEY: ""
    # AWS_DEBUG: false
    # AWS_MAX_RETRIES: 20
    # LOG_LEVEL: ""

  nodeSelector: {}
    # node-role.kubernetes.io/node: "true"
    # tier: cs

  tolerations: {}
#    - key: "node-role.kubernetes.io/master"
#      effect: NoSchedule

  podAnnotations: {}
    # iam.amazonaws.com/role: alb-ingress-controller

  podLabels: {}

  # How often (in seconds) to check operator readiness
  readinessProbeInterval: 10

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 100Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi

  service:
    port: 8080

    annotations: {}
      # prometheus.io/scrape: "true"

    labels: {}

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true

  ## Ignored if rbac.create is true
  serviceAccountName: default

sidecarContainers: {}
  ## Additional containers to be added to the alb-ingress-controller pod.
  #  - name: my-sidecar
  #    image: nginx:latest
